### PR TITLE
feat(serviceinfo): add struct

### PR DESCRIPTION
**Pull request by aaravm**
- **New Features**:
    - Introduced the ServiceInfo class to handle details of any implementation of the main GA4GH API and return its details.
- **Tests**:
    - Added a unit test to verify the functionality of the ServiceInfo class using Funnel.

## Summary by Sourcery

This pull request introduces the ServiceInfo class to manage and retrieve details of any implementation of the main GA4GH API. Additionally, a unit test has been added to ensure the functionality of the ServiceInfo class.

- **New Features**:
    - Introduced the ServiceInfo class to handle details of any implementation of the main GA4GH API and return its details.
- **Tests**:
    - Added a unit test to verify the functionality of the ServiceInfo class using Funnel.

### CODE REVIEW

**Review by pavelnikonorov — APPROVED** [review]
LGTM!

**Review by uniqueg — CHANGES_REQUESTED** [review]
At this point, we don't have the `models`, `transport` and `configuration` modules in the code base, right? So shouldn't we first have PRs that add these, before merging this?

**Comment by aaravm** [comment]
The models are being built by the script in the cicd, so thats not a problem, but if you want to maintain continuity, this PR can be merged after #30, after `transport` and `configuration` classes have been merged

**Comment by uniqueg** [comment]
If you add the docs and tests like in #30, as well as a relevant update of `README.md`, this PR would also be ready to go (after merging #30 into `main` and then merging `main` into _this_ branch, of course). Shouldn't be too much work, so maybe prioritize before building too much on unmerged code, @aaravm.

**Comment by aaravm** [comment]
Hey @uniqueg, I have separated the unit tests to a new folder `tests`, and have added normal unit tests and docs for serviceinfo. I think this PR can be merged

**Review by uniqueg — APPROVED** [review]

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
